#!/bin/bash

basepath="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

function mzx_alias_run
{
	("$basepath/MZX.sh" "$@" & )

	# Sleep briefly to let any MZX startup messages pass
	sleep .1
}

alias 100g="mzx_alias_run 1.00g"
alias 101="mzx_alias_run 1.01"
alias 102="mzx_alias_run 1.02"
alias 103="mzx_alias_run 1.03"
alias 202="mzx_alias_run 2.02"
alias 204="mzx_alias_run 2.04"
alias 207="mzx_alias_run 2.07"
alias 250="mzx_alias_run 2.50"
alias 251="mzx_alias_run 2.51"
alias 251s1="mzx_alias_run 2.51s1"
alias 251s2="mzx_alias_run 2.51s2"
alias 251s3="mzx_alias_run 2.51s3"
alias 251s31="mzx_alias_run 2.51s3.1"
alias 251s32="mzx_alias_run 2.51s3.2"
alias mzxak="mzx_alias_run ak"
alias 26="mzx_alias_run 2.6"
alias 260="mzx_alias_run 2.6"
alias 261="mzx_alias_run 2.61"
alias 262="mzx_alias_run 2.62"
alias 262b="mzx_alias_run 2.62b"
alias 265="mzx_alias_run 2.65"
alias 268="mzx_alias_run 2.68"
alias 269="mzx_alias_run 2.69"
alias 269b="mzx_alias_run 2.69b"
alias 269c="mzx_alias_run 2.69c"
alias 270="mzx_alias_run 2.70"

alias 280="mzx_alias_run 2.80"
alias 280b="mzx_alias_run 2.80b"
alias 280c="mzx_alias_run 2.80c"
alias 280d="mzx_alias_run 2.80d"
alias 280e="mzx_alias_run 2.80e"
alias 280f="mzx_alias_run 2.80f"
alias 280g="mzx_alias_run 2.80g"
alias 280h="mzx_alias_run 2.80h"

alias 281="mzx_alias_run 2.81"
alias 281b="mzx_alias_run 2.81b"
alias 281c="mzx_alias_run 2.81c"
alias 281d="mzx_alias_run 2.81d"
alias 281e="mzx_alias_run 2.81e"
alias 281f="mzx_alias_run 2.81f"
alias 281g="mzx_alias_run 2.81g"
alias 281h="mzx_alias_run 2.81h"

alias 282="mzx_alias_run 2.82"
alias 282b="mzx_alias_run 2.82b"

alias 283="mzx_alias_run 2.83"

alias 284="mzx_alias_run 2.84"
alias 284b="mzx_alias_run 2.84b"
alias 284c="mzx_alias_run 2.84c"

alias 290="mzx_alias_run 2.90"
alias 290b="mzx_alias_run 2.90b"
alias 290c="mzx_alias_run 2.90c"
alias 290d="mzx_alias_run 2.90d"

alias 291="mzx_alias_run 2.91"
alias 291b="mzx_alias_run 2.91b"
alias 291c="mzx_alias_run 2.91c"
alias 291d="mzx_alias_run 2.91d"
alias 291e="mzx_alias_run 2.91e"
alias 291f="mzx_alias_run 2.91f"
alias 291g="mzx_alias_run 2.91g"
alias 291h="mzx_alias_run 2.91h"
alias 291i="mzx_alias_run 2.91i"
alias 291j="mzx_alias_run 2.91j"

alias 292="mzx_alias_run 2.92"
alias 292b="mzx_alias_run 2.92b"
alias 292c="mzx_alias_run 2.92c"
alias 292d="mzx_alias_run 2.92d"
alias 292e="mzx_alias_run 2.92e"
alias 292f="mzx_alias_run 2.92f"

alias 293="mzx_alias_run 2.93"
alias 293b="mzx_alias_run 2.93b"
alias 293c="mzx_alias_run 2.93c"
