#!/bin/bash

if [ -z $1 ] || [ -z $2 ] || [ -z $3 ]; then
	echo "USAGE: ./dl [vault id] [file SHA-256] [folder after extraction]"
	exit
fi

format=$4
[ -z $format ] && format=zip

rm -f $3.$format
rm -rf $3

echo "DL: $3"
wget -cq http://vault.digitalmzx.net/download.php?rid\=$1\&f\=$2 -O $3.$format

case $format in
	zip)
		7za x $3.zip -o$3 > /dev/null
		;;

	tar.gz)
		mkdir -p $3
		tar -xzf $3.tar.gz -C $3
		;;

	tar.bz2)
		mkdir -p $3
		tar -xjf $3.tar.bz2 -C $3
		;;

	tar.xz)
		mkdir -p $3
		tar -xJf $3.tar.xz -C $3
		;;
esac

rm -f $3.$format
