#!/bin/bash

if [ -z $1 ] || [ -z $2 ] || [ -z $3 ]; then
	echo "USAGE: ./dl [vault id] [file SHA-256] [folder after extraction]"
	exit
fi

rm -f $3.zip
rm -rf $3

echo "DL: $3"
wget -cq http://vault.digitalmzx.net/download.php?rid\=$1\&f\=$2 -O $3.zip
7za x $3.zip -o$3 > /dev/null

rm -f $3.zip
